{{- if .Values.secretManager.enabled }}
{{- if .Values.secretManager.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.secretManager.serviceAccount.name }}
  labels:
    {{- include "main.labels" . | nindent 4 }}
  {{- with .Values.secretManager.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}